import 'package:hive/hive.dart';
import '../../../features/auth/domain/models/user.dart';
import '../../../features/session_logger/domain/models/training_session.dart';

/// Registers all Hive type adapters for local storage.
/// 
/// This should be called during app initialization before opening any boxes.
void registerHiveAdapters() {
  // Note: Actual adapters will be generated by hive_generator
  // after adding @HiveType annotations to domain models
  
  // Type IDs are defined in app_constants.dart
  // Hive.registerAdapter(UserAdapter());              // typeId: 0
  // Hive.registerAdapter(TrainingSessionAdapter());   // typeId: 1
  // Hive.registerAdapter(EndAdapter());               // typeId: 2
  // Hive.registerAdapter(ArrowAdapter());             // typeId: 3
  // Hive.registerAdapter(TargetFaceAdapter());        // typeId: 4
  
  // TODO: After adding @HiveType and @HiveField annotations to models,
  // run: flutter pub run build_runner build --delete-conflicting-outputs
}

/// Open all required Hive boxes
Future<void> openHiveBoxes() async {
  // Open cache box for offline data
  await Hive.openBox('cache_box');
  
  // Open sessions box for training sessions
  await Hive.openBox<TrainingSession>('sessions_box');
  
  // Open user box for user profiles
  await Hive.openBox<User>('user_box');
}

/// Close all Hive boxes
Future<void> closeHiveBoxes() async {
  await Hive.close();
}

/// Clear all cached data (useful for logout)
Future<void> clearHiveCache() async {
  final cacheBox = Hive.box('cache_box');
  await cacheBox.clear();
  
  final sessionsBox = Hive.box('sessions_box');
  await sessionsBox.clear();
}
